services:
  app:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_started
    restart: on-failure
  db:
    image: "postgres:13"
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
volumes:
  postgres:
